# anytime we are using required we need to have super user permissions
sudo: required

# automatically install docker into the travis container (we need a copy of docker ready to go)
services:
  - docker

# series of commands or steps that happen before we run our tests
# in our case we want to build our docker image before our tests run
# . use the current directory for context
before_install:
  - docker build -t hd719/docker-react -f Dockerfile.dev .

# Commands needed to run our test suite
script:
  - docker run -e CI=true hd719/docker-react npm run test

# Exactly how to deploy our application to AWS
deploy:
  provider: elasticbeanstalk # telling travis to use elasticbeanstalk for deployment
  region: "us-east-2" # this comes from the url of our app from AWS
  app: "docker-react" # name of the app
  env: "DockerReact-env" # Env where our app is running
  # travis will take all the files in our repository and zip them up into 1 single file and then copy it into Amazon s3 bucket (hardrive running on AWS)
  # when you create the env for the app a s3 bucket is already created for you
  bucket_name: "elasticbeanstalk-us-east-2-234599825231"
  bucket_path: "docker-react"
  on:
    branch: master
    # means anytime we push code to master then run the `deploy` script
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
